# Generated by Django 5.2 on 2025-04-20 18:45

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(verbose_name=django.db.models.fields.TextField)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
